
mail:
  host: smtp.gmail.com
  port: 587
  username: officialadda2022@gmail.com # gmail id of stone adda
  password: xmbdmaamrefexmtr # password of Stone add gmail account
  protocol: smtp
  tls: true
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com
cloud:
  aws:
    region:
      static: us-east-1 # location of aws account
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAVDEBZZJ3723N7EHN #access key of Aws account for dynamo db
      secret-key: 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 #secret key of Aws account for dynamo db
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 338445782950-vd98du462u7lho715lu773fievhskon7.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile